version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: .${FRONTEND_PATH_PREFIX}frontend.dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - PATH_PREFIX=${FRONTEND_PATH_PREFIX}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./frontend/frontend/.env
    restart: always
    depends_on:
      - bff

  bff:
    container_name: bff
    build:
      context: .
      dockerfile: .${BFF_PATH_PREFIX}/bff.dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - PATH_PREFIX=${BFF_PATH_PREFIX}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "3001:3001"
    volumes:
      - ./microservices/bff:/app
      - /app/node_modules
    env_file:
      - ./microservices/bff-service/.env
    restart: always
    depends_on:
      - product

  product:
    container_name: product
    build:
      context: .
      dockerfile: .${PRODUCT_PATH_PREFIX}product.dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - PATH_PREFIX=${PRODUCT_PATH_PREFIX}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "3002:3002"
    volumes:
      - ./microservices/product:/app
      - /app/node_modules
    env_file:
      - ./microservices/product-service/.env
    restart: always